name: Docker Pull Image
run-name: ${{github.actor}}POC ${{github.base_ref}}
on: [pull_request, push]

jobs:
  #check-npm:
    #runs-on: windows-latest
    #steps:
    #- name: check npm
      #run: |
        #npm --version
        #npx --version
        #python --version
        #python3 --version
        ##python3 -c "import subprocess; result = subprocess.run(['npm','--version'],capture_output=True,shell=True); print(result.stdout.strip())"
        #npm install json yaml path
        #python3 -c "import subprocess; result = subprocess.run(['npm','list'],capture_output=True,shell=True); print(result.stdout.strip())"
  #check-npm-mac:
    #runs-on: macos-11
    #steps:
    #- name: check npm
      #run: |
        #npm --version
        #npx --version
        #python --version
        #python3 --version
        #python3 -c "import subprocess; result = subprocess.run(['npm','--version'],capture_output=True); print(result.stdout.strip())"

  install_macports:
    runs-on: macos-11
    steps:
    - name: Install dependencies
      run: |
        brew install wget sqlite
    - name: Install macports package manager
      run: |
        wget https://github.com/macports/macports-base/releases/download/v2.8.1/MacPorts-2.8.1-11-BigSur.pkg
        sudo installer -pkg MacPorts-2.8.1-11-BigSur.pkg -target /
        rm -rf MacPorts-2.8.1-11-BigSur.pkg
    - name: Install ports
      run: |
        #sudo /opt/local/bin/port selfupdate
        sudo /opt/local/bin/port install nano
    #- name: Get files
      #run: |
        #ls /opt/local/var/macports/registry
    #- name: Get ports
      #run: |
        #sqlite3 /opt/local/var/macports/registry/registry.db "select * from ports where name='neovim'"
    #- name: Download and compile
      #run: |
        ##wget https://github.com/wazuh/wazuh/archive/refs/heads/dev-15877-macport_pkgs-implementation.zip
        #wget https://github.com/wazuh/wazuh/archive/refs/heads/dev-15877-macport_pkgs-implementation-rebased.zip
        #unzip dev-15877-macport_pkgs-implementation-rebased.zip
        #make deps -C wazuh-dev-15877-macport_pkgs-implementation-rebased/src TARGET=agent -j2
        #make -C wazuh-dev-15877-macport_pkgs-implementation-rebased/src TARGET=agent -j2
    #- name: Execute data provider
      #run: |
        #wazuh-dev-15877-macport_pkgs-implementation-rebased/src/data_provider/build/bin/sysinfo_test_tool --packages
    ##- name: Setup-python
      ##uses: actions/setup-python@v4
      ##with:
        ##python-version: '3.9'
        ##cache: 'pip' # caching pip dependencies
      ##run: pip install -r requirements.txt
    #- name: Execute pytest
      #run: |
        #pip3 install -r wazuh-dev-15877-macport_pkgs-implementation-rebased/src/data_provider/qa/requirements.txt
        #cd wazuh-dev-15877-macport_pkgs-implementation-rebased/src/data_provider
        #sudo python3 -m pytest -vv qa/


